import Footer from "@/Component/Footer/Footer";
import Navbar from "@/Component/Navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }) => {
  return (
    <div>
      <div className="">
        <Navbar />
        {children}
        <Footer />
      </div>
    </div>
  );
};

export default Layout;
